FROM ros:humble-ros-base

# ROS deps (Festival removed)
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-tk \
    tk \
    alsa-utils \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-tf2-ros \
    ros-humble-tf2-geometry-msgs \
    ros-humble-tf2-py \
    ros-humble-geometry-msgs \
    ros-humble-visualization-msgs \
    ros-humble-rviz2 \
    ros-humble-rqt \
    ros-humble-rqt-common-plugins \
    && rm -rf /var/lib/apt/lists/*

# Install Kyutai Pocket TTS and dependencies
RUN pip3 install --upgrade --no-cache-dir \
    torch \
    "numpy>=2.0.0" \
    "scipy>=1.14.0" \
    soundfile \
    huggingface_hub \
    pocket-tts

# Source ROS automatically in interactive shells
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc


# Install audio_common_msgs
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-audio-common-msgs \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /workspace

# Laptop battery monitor (laptop_battery_monitor.py)
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-psutil \
    && rm -rf /var/lib/apt/lists/*